---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-learning
spec:
  selector:
    matchLabels:
      app: springboot-learning
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-learning
    spec:
      containers:
        - name: springboot-learning
          image: springboot-learning:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: learning
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
            - name: DB_PORT # Setting Database password
              value: "3307"

# This seperator --- below is MANDATORY!!!
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: learning-service
spec:
  ports:
    - protocol: "TCP"
      port: 8081    # Port inside the cluster
      targetPort: 8081   # Port exposed to the outside
  selector:
    app: springboot-learning
  type: NodePort
